---
- name: install rpms for docker
  yum:
    name="{{ item }}"
    state=latest
    update_cache=yes
  with_items:
    - device-mapper-persistent-data
    - lvm2
    - docker
    - kubernetes

- name: enable docker
  service: name=docker enabled=yes state=started
